apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-configmap
data:
  REDIS_USER: {{ .Values.redis.REDIS_USER | quote }}
  HOSTNAME: {{ .Values.redis.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.redis.REDIS_PORT | quote }}
